version: 2.1
orbs:
  protobuf: izumin5210/protobuf@0.1.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update
      - protobuf/install

      - run: mvn clean test jacoco:report coveralls:report
