version: 2.1
orbs:
  protobuf: izumin5210/protobuf@0.1.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-buster

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update
      - protobuf/install
      - run:
          name: "Install protoc plugin"
          command: |
            curl -L https://github.com/grpc/grpc-web/releases/download/1.0.7/protoc-gen-grpc-web-1.0.7-linux-x86_64 --output protoc-gen-grpc-web
            sudo mv protoc-gen-grpc-web /usr/local/bin/
            chmod +x /usr/local/bin/protoc-gen-grpc-web

      # Restore the saved cache after the first run or if `pom.xml` has changed. Read about caching dependencies:
      # https://circleci.com/docs/2.0/caching/
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn clean verify jacoco:report

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: bash <(curl -s https://codecov.io/bash)
